### ISSUE TITLE
as a client I want to see  the items ifor sale on the site with their prices 

### ISSUE THREAD

**Issue by kesamercy** [software-for-change/org-farm#44]
**### Tasks**

- [x] determine what information the customers want to see.

- the price
- the name 
- the image of the food
- quantity feature

- [x] show that information in a dvi

- [x] show the items in the db for the food in the inventory
- [x] attach a price to the items for sale
