### ISSUE TITLE
Website design for UI

### ISSUE THREAD

**Issue by kesamercy** [software-for-change/org-farm#46]
Ideas for UI 

selling the items page 

https://www.ernolaszlo.com/

ideas for the images in the background 
https://colorlib.com/wp/wp-content/uploads/sites/2/origine-farming-wordpress-theme.jpg

sample images for banner
https://www.freepik.com/free-photos-vectors/wood-fruit

images for the vegetables on the site
https://www.freepngimg.com/png/5509-cabbage-png-image/download

website design for displaying the images in the gallery
https://phppot.com/php/simple-php-shopping-cart/

have the images in tiles and then make the color of the tile gray and after log in make the tile white.

### the welcome client page

- [ ] the top part has images of fruits with opaque bkgd. combo of tutoring site + the sample images for the bkgd up there
- [ ] the remaining part of the page is white with the arrangmeent of the selling items sample page 
- [ ] the top right corner has a gif of the plants. 

- [ ] when the user logs in to buy the page turns white
- [ ] when the user is not logged in the page showing the items is gray(?)
